//! The shared design language: small builders every family uses to decorate its surfaces the same way, so
//! that components generated by different families look like they belong to the same army.
//!
//! The language (see docs/design/06-art-direction.md):
//! * **Value split.** Upper surfaces in Primary, lower hull and running gear in Secondary or Dark.
//! * **One bold accent.** A Trim stripe or chevron per component, never more than about a tenth of its surface.
//! * **Energy.** Thin Glow lines along a waist or edge, glowing sensor "eyes", heat glow under dark vents.
//! * **Layered plates.** Armour plates laid proud of the surface; their chamfers catch the light.
//!
//! Most builders work on a planar quad given by four corners in order around the face: `q[0] -> q[1]` is the
//! face's `u` direction and `q[0] -> q[3]` its `v` direction.

use crate::geom::{v3, V3};
use crate::schema::{Axis, Node, Slot};

pub type Quad = [V3; 4];

/// Point at (u, v) on a quad (bilinear).
pub fn at(q: &Quad, u: f64, v: f64) -> V3 {
    let a = q[0] + (q[1] - q[0]) * u;
    let b = q[3] + (q[2] - q[3]) * u;
    a + (b - a) * v
}

/// Outward normal of a quad, given a point known to be inside the solid it belongs to.
pub fn normal(q: &Quad, inside: V3) -> V3 {
    let n = (q[1] - q[0]).cross(q[3] - q[0]).norm();
    let c = (q[0] + q[1] + q[2] + q[3]) * 0.25;
    if n.dot(c - inside) < 0.0 {
        -n
    } else {
        n
    }
}

pub fn hull(points: Vec<V3>, mat: &str, slot: Slot, shell: Option<f64>, chamfer: f64) -> Node {
    Node::Hull { points: points.iter().map(|p| p.arr()).collect(), at: [0.0; 3], rot: [0.0; 3], mat: mat.into(), slot, shell, chamfer }
}

pub fn bx(size: [f64; 3], at: V3, mat: &str, slot: Slot, chamfer: f64) -> Node {
    Node::Box { size, taper: None, shift: None, at: at.arr(), rot: [0.0; 3], mat: mat.into(), slot, shell: None, chamfer }
}

#[allow(clippy::too_many_arguments)]
pub fn cyl(radius: f64, length: f64, axis: Axis, segments: u32, taper: f64, at: V3, mat: &str, slot: Slot, shell: Option<f64>, chamfer: f64) -> Node {
    Node::Cylinder { radius, length, axis, segments, taper, at: at.arr(), rot: [0.0; 3], mat: mat.into(), slot, shell, chamfer }
}

pub fn sphere(radius: f64, at: V3, mat: &str, slot: Slot) -> Node {
    Node::Sphere { radius, segments: 8, scale: None, at: at.arr(), rot: [0.0; 3], mat: mat.into(), slot, shell: None, chamfer: 0.0 }
}

pub fn beam(from: V3, to: V3, size: [f64; 2], up: V3, mat: &str, slot: Slot, chamfer: f64) -> Node {
    Node::Beam { from: from.arr(), to: to.arr(), size, end: None, up: up.arr(), mat: mat.into(), slot, shell: None, chamfer }
}

/// A plate covering the region (u0..u1, v0..v1) of a face, standing `t` proud of it (embedded slightly so it
/// meets the surface cleanly). `inset` pulls the outer face in from the edges, giving a bevelled plate.
#[allow(clippy::too_many_arguments)]
pub fn plate(q: &Quad, inside: V3, u: (f64, f64), v: (f64, f64), t: f64, inset: f64, mat: &str, slot: Slot) -> Node {
    let n = normal(q, inside);
    let corners = [at(q, u.0, v.0), at(q, u.1, v.0), at(q, u.1, v.1), at(q, u.0, v.1)];
    let c = (corners[0] + corners[1] + corners[2] + corners[3]) * 0.25;
    let mut pts = Vec::with_capacity(8);
    for p in corners {
        pts.push(p - n * (0.3 * t));
        let toward = c - p;
        let pull = if toward.len() > 1e-9 { toward.norm() * inset.min(0.45 * toward.len()) } else { V3::ZERO };
        pts.push(p + n * t + pull);
    }
    hull(pts, mat, slot, None, 0.0)
}

/// A thin glowing line from `a` to `b` lying on a surface with outward normal `n`.
pub fn glow_line(a: V3, b: V3, n: V3, width: f64) -> Node {
    let t = width * 0.5;
    beam(a + n * (t * 0.3), b + n * (t * 0.3), [width, t], n, "fittings", Slot::Glow, 0.0)
}

/// A row of `count` dark vent slats across the region (u0..u1, v0..v1) of a face, with a glowing heat strip under
/// them.
pub fn vents(q: &Quad, inside: V3, u: (f64, f64), v: (f64, f64), count: usize, t: f64, out: &mut Vec<Node>) {
    let n = normal(q, inside);
    out.push(plate(q, inside, u, v, t * 0.4, 0.0, "fittings", Slot::Glow));
    for k in 0..count {
        let f0 = v.0 + (v.1 - v.0) * (k as f64 + 0.15) / count as f64;
        let f1 = v.0 + (v.1 - v.0) * (k as f64 + 0.75) / count as f64;
        out.push(plate(q, inside, u, (f0, f1), t, 0.0, "fittings", Slot::Dark));
    }
    let _ = n;
}

/// A glowing sensor eye set into a surface: a dark socket with a bright lens.
pub fn eye(at: V3, n: V3, r: f64, out: &mut Vec<Node>) {
    let axis = n.norm();
    out.push(beam(at - axis * r, at + axis * (0.4 * r), [2.0 * r, 2.0 * r], axis.any_perp(), "fittings", Slot::Dark, 0.15 * r));
    out.push(sphere(0.75 * r, at + axis * (0.45 * r), "glass", Slot::Glow));
}

/// Shorthand for a point.
pub fn p(x: f64, y: f64, z: f64) -> V3 {
    v3(x, y, z)
}
